<a href="https://colab.research.google.com/github/MrSamuel137/ggle-clb-pymarket-001/blob/main/investpy_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install git+https://github.com/alvarobartt/investpy.git@master

import investpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/alvarobartt/investpy.git@master
  Cloning https://github.com/alvarobartt/investpy.git (to revision master) to /tmp/pip-req-build-fva4xds5
  Running command git clone -q https://github.com/alvarobartt/investpy.git /tmp/pip-req-build-fva4xds5
Requirement already satisfied: Unidecode>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from investpy==1.0.8) (1.3.4)
Requirement already satisfied: setuptools>=41.2.0 in /usr/local/lib/python3.7/dist-packages (from investpy==1.0.8) (57.4.0)
Requirement already satisfied: numpy>=1.17.2 in /usr/local/lib/python3.7/dist-packages (from investpy==1.0.8) (1.21.6)
Requirement already satisfied: pandas>=0.25.1 in /usr/local/lib/python3.7/dist-packages (from investpy==1.0.8) (1.3.5)
Requirement already satisfied: lxml>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from investpy==1.0.8) (4.9.1)
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.7/dist-packages (from investpy==1.0.8) (2.28.1)
Requirement already satisfied: pytz>=2019.3 in /usr/local/lib/python3.7/dist-packages (from investpy==1.0.8) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.1->investpy==1.0.8) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.1->investpy==1.0.8) (1.15.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.22.0->investpy==1.0.8) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.22.0->investpy==1.0.8) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.22.0->investpy==1.0.8) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.22.0->investpy==1.0.8) (1.24.3)

In [10]:
df = investpy.get_stock_historical_data(stock='PETR4',
                                        country='Brazil',
                                        from_date='01/01/2022',
                                        to_date='04/09/2022')

df

             Open   High    Low  Close     Volume Currency
Date
2022-01-03  28.54  29.22  28.53  29.09   52704700      BRL
2022-01-04  29.16  29.40  28.91  29.20   51739200      BRL
2022-01-05  29.19  29.27  27.94  28.07   78459800      BRL
2022-01-06  28.29  28.65  27.84  28.05   61163100      BRL
2022-01-07  28.11  28.29  27.82  28.18   47507600      BRL
...           ...    ...    ...    ...        ...      ...
2022-08-29  33.53  35.07  33.45  34.48   72914496      BRL
2022-08-30  33.98  34.22  32.28  32.43   98286304      BRL
2022-08-31  32.04  33.44  31.83  33.23  113976000      BRL
2022-09-01  33.42  33.95  32.77  33.85   68756704      BRL
2022-09-02  34.46  34.57  33.26  33.42   81579000      BRL

[170 rows x 6 columns]